=begin
#ORY Oathkeeper

#ORY Oathkeeper is a reverse proxy that checks the HTTP Authorization for validity against a set of rules. This service uses Hydra to validate access tokens and policies.

The version of the OpenAPI document: 0.40.8
Contact: hi@ory.am
Generated by: https://openapi-generator.tech
Generator version: 7.7.0

=end

module OryOathkeeperClient
  VERSION = '0.40.8'
end
